sonar.projectKey=hafizumerabid-creator_cohort-9-mern-16473-muhammad
sonar.organization=hafizumerabid-creator


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=cohort-9-mern-16473-muhammad
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=backend
sonar.tests=backend/tests
sonar.exclusions=backend/tests/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8